version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Maps host port 8000 to container port 8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Maps host port 5173 to container port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
